sudo: false
dist: trusty
language: node_js
node_js: node

cache:
  directories:
  - $HOME/.npm
  - node_modules

before_install:
- travis_retry gem install s3_website -v 3.4.0
- travis_retry pip install awscli --upgrade --user

install:
- npm install

script:
- npm run build
- npm test

after_script:
- ./s3_deploy.sh
