sudo: false
dist: trusty
language: node_js
node_js:
  - "12"

cache:
  directories:
  - $HOME/.npm
  - node_modules

before_install:
- travis_retry gem install s3_website -v 3.4.0
- travis_retry pyenv global 3.6
- travis_retry pip install awscli --upgrade --user

install:
- npm install

script:
- npm run build
- npm test

after_success:
- ./s3_deploy.sh
