sudo: false
language: node_js
node_js: node

cache:
  directories:
    - $HOME/.npm

before_install:
  - travis_retry npm install --global lerna

install:
  - lerna bootstrap

script:
  - lerna run build --scope=@concord-consortium/text-decorator
  - lerna run build --scope=@concord-consortium/glossary-plugin
  - npm test

after_script:
  - yarn run report_coverage
