sudo: false
language: node_js
node_js: node

cache:
  directories:
    - $HOME/.npm
    - node_modules

before_install:
  - travis_retry gem install s3_website -v 3.4.0
  - travis_retry pip install awscli --upgrade --user
  - travis_retry npm install --global lerna

install:
  - travys_retry npm install
  - lerna bootstrap

script:
  - lerna run build --scope=@concord-consortium/text-decorator
  - lerna run build --scope=@concord-consortium/glossary-plugin
  - npm test

after_script:
  - yarn run report_coverage
  - ./packages/glossary-plugin/s3_deploy.sh
