sudo: false
dist: trusty
language: node_js
node_js:
  - "12"

cache:
  directories:
  - $HOME/.npm
  - node_modules

before_install:
- travis_retry gem install s3_website -v 3.4.0
# the next commands is to fix "SSLContext object is not available" error in awscli install
- travis_retry pip install requests[security]
- travis_retry pip install awscli --upgrade --user

install:
- npm install

script:
- npm run build
- npm test

after_success:
- ./s3_deploy.sh
