import { IGlossaryModelAuthoringInitialData } from "../../types";

export const demoGlossary: IGlossaryModelAuthoringInitialData = {
  name: "Demo Glossary",
  json: {
    askForUserDefinition: true,
    autoShowMediaInPopup: true,
    showIDontKnowButton: true,
    showSideBar: false,
    enableStudentLanguageSwitching: true,
    enableStudentRecording: false,
    definitions: [
      {
        "word": "cluster housing",
        "definition": "When developers build a community, they can build the houses closer together and leave other areas open and undeveloped where they plant trees and other plants that will soak up the rain. This reduces flooding and allows water to soak back into the ground.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/cluster-housing-high.jpg",
        "imageCaption": "Shared open space in the neighborhood.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/ClusterHousing.mp4",
        "videoCaption": "Houses grouped around shared garden and grass."
      },
      {
        "word": "composting",
        "definition": "The controlled biological decomposition of organic material, such as sewage sludge, animal manures, or crop residues, in the presence of air to form a humus-like material.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/composting-high.jpg",
        "imageCaption": "Left over scraps used to make organic fertilizer.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Composting.mp4",
        "videoCaption": "Left over scraps used to make organic fertilizer."
      },
      {
        "word": "conservation practice",
        "definition": "Control measures consisting of managerial, vegetative, and structural practices to reduce runoff and the loss of soil, promote infiltation and absorbtion of pollutants, and protect water quality. Also known as best management practices (BMPs).",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/conservation-practice-high.jpg",
        "imageCaption": "All these activities help the rivers be healthy and free of pollutants",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/ConservationPractice.mp4",
        "videoCaption": "Rain gardens, no-till agriculture, and pervious surfaces are conservation practices that help the rivers be healthy and free of pollutants"
      },
      {
        "word": "developed land",
        "definition": "Land areas where humans have altered the landscape and installed constructed materials (asphalt, concrete, buildings, etc) over 30 percent or more of the area. ",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/developed-land-high.jpg",
        "imageCaption": "Humans building around rivers and streams. ",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/DevelopedLand.mp4",
        "videoCaption": "Many houses and roads built on open land."
      },
      {
        "word": "elevation",
        "definition": "The distance above sea level.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/elevation-high.jpg",
        "imageCaption": "Mountains rising above sea level.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Elevation.mp4",
        "videoCaption": "Mountains rising above valleys."
      },
      {
        "word": "erosion",
        "definition": "The wearing away of land surfaces by wind or water, intensified by land-clearing practices related to farming, residential or industrial development, road building, or logging.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/erosion-lg.jpg",
        "imageCaption": "Flowing water causes land to wash away.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/erosion.mp4",
        "videoCaption": "During a large rainstorm, water can cause land cover to move."
      },
      {
        "word": "evaporation",
        "definition": "The process of changing water from a liquid (water) to a gas (water vapor) by adding energy (heat). Water vapor is water molecules that are suspended in the air. Warm air has more energy and can contain more water molecules, which is why it often feels more humid in warm weather.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/evaporation-high.jpg",
        "imageCaption": "Water from the lake becomes fog.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Evaporation.mp4",
        "videoCaption": "As the day warms up, the water in the path moves into the air as vapor."
      },
      {
        "word": "evapotranspiration",
        "definition": "The combined processes by which water moves from the land to the atmosphere by transpiration from plants, and by evaporation from surface waters, soils, and other moist surfaces.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/evapotranspiration-high.jpg",
        "imageCaption": "Forests release moisture from the trees and the soils. ",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Evapotranspiration.mp4",
        "videoCaption": "Forests release moisture from the trees and the soils."
      },
      {
        "word": "flood ",
        "definition": "Any relatively high streamflow that overflows the natural or artificial banks of a stream. Floods may be caused by long-lasting rainfall over a broad area, locally intense thunderstorms, rapid melting of snowpack, or obstructions to normal stream flows.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/flooding-lg.jpg",
        "imageCaption": "Rivers overflow with large rainfalls.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Flooding.mp4",
        "videoCaption": "During a big storm, road surfaces will not allow the water to soak in."
      },
      {
        "word": "green roof",
        "definition": "A conservation practice where the roof of a building is partially or completely covered with vegetation and a growing medium, planted over a waterproofing membrane. It may also include additional layers such as a root barrier and drainage and irrigation systems.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/green-roof-lg.jpg",
        "imageCaption": "Grass and vegetation are planted on roof tops. ",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/GreenRoof.mp4",
        "videoCaption": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/GreenRoof.mp4"
      },
      {
        "word": "groundwater",
        "definition": "Water found underground in the cracks and spaces (pores) in soil, sand and rock. Groundwater is stored in and moves slowly through geologic formations of soil, sand and rocks called aquifers.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/groundwater-high.jpg",
        "imageCaption": "A pipe going down into the earth shows water in deep soil layers.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/GroundWater.mp4",
        "videoCaption": "Wells allow you to bring water up from underground. "
      },
      {
        "word": "impervious",
        "definition": "A land surface area that does not have connected pores and cannot allow liquids and gases (including water) to infiltrate the ground which results in more runoff.  ",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/impervious-high.jpg",
        "imageCaption": "Roads and side walks often prevent water from soaking into the soil.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Impervious.mp4",
        "videoCaption": "Puddles form when rain water can not reach the soil."
      },
      {
        "word": "infrastructure",
        "definition": "The physical and organizational structures and facilities (e.g., buildings, roads, and power supplies) built by humans that are needed for the operation of a society or organization.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/infrastructure-lg.jpg",
        "imageCaption": "Underground tubing carries rain and waste water outside the building.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Infrastructure.mp4",
        "videoCaption": "This kind of tubing and canal allows for the water to move very fast and create electricity."
      },
      {
        "word": "irrigation",
        "definition": "Application of water or wastewater to land areas to supply the water and nutrient needs of plants.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/irrigation-high.jpg",
        "imageCaption": "Water from rivers or aquifers is spread on the crops to produce food.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Irrigation.mp4",
        "videoCaption": "Crops receive water from a nearby river to help them grow"
      },
      {
        "word": "landfill",
        "definition": "A disposal site for the burial of waste materials.  Wastes in landfills are often spread in layers, compacted to the smallest practical volume, and covered by capping materials and soils.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/landfill-high.jpg",
        "imageCaption": "Waste from houses and industry that cannot be reused or recycled. ",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Landfill.mp4",
        "videoCaption": "The truck drops waste that was picked up from our neighborhoods."
      },
      {
        "word": "nonpoint source pollution",
        "definition": "Pollution from different sources that occur over a wide area and are not easily identified from a single source.  Nonpoint source pollution often results from runoff that picks up and carries natural and human-made pollutants into lakes, rivers, wetlands, coastal waters, and groundwater.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/nonpoint-source-pollution-high.jpg",
        "imageCaption": "Fish cannot live in polluted water.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/nonpoint-source-pollution.mp4",
        "videoCaption": "The runoff tranports garbage and contaminants to the rivers."
      },
      {
        "word": "no-till agriculture",
        "definition": "An agricultural conservation practice (BMP) whereby farmers plant crops without disturbing the soil or removing the plants that are already there. No-till agriculture improves the infiltration rate of the soil, reduces erosion, and builds the organic matter and nutrient cycling in the soil.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/no-till-agriculture-high.jpg",
        "imageCaption": "The farmers look at a crop that is planted to protect the soil.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/NoTillAgriculture.mp4",
        "videoCaption": "Organic matter builds up in the farm soil when it is not tilled."
      },
      {
        "word": "pervious",
        "definition": "A land surface area that has connected pores which allows liquids and gases (including water) to pass through the material and infiltrate into the ground. ",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/pervious-high.jpg",
        "imageCaption": "This type of concrete allows the rain water to pass through it.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Pervious.mp4",
        "videoCaption": "Water goes through this type of asphalt."
      },
      {
        "word": "photosynthesis",
        "definition": "The process by which plants and some other organisms use sunlight to make foods from carbon dioxide and water. Photosynthesis in plants generally involves the green pigment chlorophyll and generates oxygen as a byproduct. ",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/photosynthesis-high.jpg",
        "imageCaption": "Plants harvest solar energy through their leaves to grow.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Photosynthesis.mp4",
        "videoCaption": "These leaves are utilizing solar energy to make the plant grow."
      },
      {
        "word": "point source pollution",
        "definition": "Any single identifiable source of pollution from which pollutants are discharged, such as a pipe, ditch, ship or factory smokestack. Factories and sewage treatment plants are two common types of point sources.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/point-source-pollution-lg.jpg",
        "imageCaption": "Pipes from factories carry polluted water to a river.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/PointSourcePollution.mp4",
        "videoCaption": "This pipe is delivering contaminated water to a river."
      },
      {
        "word": "porous paving",
        "definition": "A conservation practice where the surface of parking areas and walkways are constructed with materials that have connected pores or spaces between the surface blocks that allow water to infiltrate into the ground. A layer of gravel is often installed below the surface to hold the water as it slowly infiltrates into the ground underneath.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/porous-paving-high.jpg",
        "imageCaption": "Bricks with spacing between can help the water reach the soil.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/PorousPaving.mp4",
        "videoCaption": "This parking lot is made from a porous material that allows the water to reach the soil."
      },
      {
        "word": "rain garden",
        "definition": "A conservation practice that reduces runoff where a shallow depression in the landscape collects rain water from a roof, driveway, or street and allows the water to slowly infiltrate into the ground. Rain gardens are often planted with native grasses and flowering perennials to enhance infiltration and evapotranspiration, help filter out pollutants, and provide food and shelter for butterflies, song birds and other wildlife. More complex rain gardens with drainage systems and amended soils are often referred to as bioretention basins.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/rain-garden-lg.jpg",
        "imageCaption": "Plants and flowers help the water reach the soil.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/RainGarden.mp4",
        "videoCaption": "The neighbors are helping build a rain garden."
      },
      {
        "word": "runoff",
        "definition": "Water that does not infiltrate into the ground and runs across the surface of the land, which can cause erosion and carry pollutants and sediment into streams, rivers, lakes, stormwater basins, or sewers.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/runnoff-high.jpg",
        "imageCaption": "Rain water runs over the land surface.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Runoff.mp4",
        "videoCaption": "Rain water runs over the land surface."
      },
      {
        "word": "sediment",
        "definition": "Particles from rocks or biological materials that have been transported by, suspended in, or deposited by air, water, or ice or that are accumulated by other natural processes. Some typical sediments are pebbles, sand, clay, silt, salts, and diatomaceous earth.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/sediment-high.jpg",
        "imageCaption": "Fine particles accumulate in the bottom of the river in areas where the water is slow.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/sediment.mp4",
        "videoCaption": "During storms, soil is washed away into the river and causes turbid waters."
      },
      {
        "word": "sewage treatment plant",
        "definition": "A municipal facility that cleans human waste water to remove contaminants before returning the water to the environment.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/sewage-treatment-plant-high.jpg",
        "imageCaption": "Waste water from our homes gets cleaned in this facility before it gets to the river.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/SewageTreatmentPlant.mp4",
        "videoCaption": "This facility waste water from our homes is cleaned before it is returned to the river."
      },
      {
        "word": "slope",
        "definition": "The angle of the land compared to the horizontal, which affects the movement of water. Water flows from higher to lower elevations, down the slopes of the land. Water will flow faster down a steep slope, and slower on a gentle slope.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/slope-high.jpg",
        "imageCaption": "The side of the mountain is not flat.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Slope.mp4",
        "videoCaption": "The slope in this mountain is so steep it creates a waterfall."
      },
      {
        "word": "temperature",
        "definition": "A measure of the amount of heat (kinetic energy) in a given area.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/temperature-lg.jpg",
        "imageCaption": "The thermometer measures a hot day.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Temperature.mp4",
        "videoCaption": "The snow melts as the air becomes warmer."
      },
      {
        "word": "transpiration",
        "definition": "The process whereby plants release water back into the atmosphere through pores (stomata) on the surface of leaves, stems, and flowers. ",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/transpiration-high.jpg",
        "imageCaption": "Leaves from trees release water to the atmosphere as vapor.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/transpiration2.mp4",
        "videoCaption": "The girl collects the moisture that the leaves release."
      },
      {
        "word": "water quality criteria",
        "definition": "Levels of water quality expected to make a body of water suitable for its designated use. Criteria are based on specific levels of pollutants that would make the water harmful if used for drinking, swimming, farming, fish production, or industrial processes.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/water-quality-criteria-high.jpg",
        "imageCaption": "The chemist analyzes a water sample to check for contaminants.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/WaterQualityCriteria.mp4",
        "videoCaption": "Many small rivers join a larger river."
      },
      {
        "word": "watershed",
        "definition": "A system defined by the area of land over which all water drains downhill through a series of streams and rivers to a common outlet (river, lake, bay or ocean).  ",
        "image": "https://project-resources.concord.org/waters/Lesson9/Images/aerial_view_Stream_Agashashok_River_8-2016_Mike_Carey.jpg",
        "imageCaption": "The mountains direct the rain water downhill to a river.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Watershed.mp4",
        "videoCaption": "The slope of the mountain directs the rain water into the lake."
      },
      {
        "word": "wetlands",
        "definition": "Land areas where the soil is almost always wet throughout most or all of the year. There may or may not be water visible at the surface.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/wetlands-high.jpg",
        "imageCaption": "Water remains on the surface of low areas.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Wetlands.mp4",
        "videoCaption": "Shallow water with plants that like to live in wet soil."
      },
      {
        "word": "drought",
        "definition": "A shortage of water due to long time periods without any precipitation. Droughts can cause a loss of vegetation, lead to wildfires, and reduce groundwater storage.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/drought-high.jpg",
        "imageCaption": "The crops die if there is not enough rain.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/drought.mp4",
        "videoCaption": "Soils with no water become infertile."
      },
      {
        "word": "soil group",
        "definition": "A classification system used to describe the ability of a soil to allow infiltration and movement of water through the soil. The soils are rated from High Infiltration to Very Slow Infiltration.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/hydrologic-soil-group-high.jpg",
        "imageCaption": "Different types of soil",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/hydrologic-soil-group.mp4",
        "videoCaption": "Different types of soil"
      },
      {
        "word": "infiltration",
        "definition": "The process of water soaking into the ground.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/infiltration-high.jpg",
        "imageCaption": "Water colored with blue ink was poured on the ground and then a hole was dug to see the pathways the water followed.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/infiltration.mp4",
        "videoCaption": "Water runs through the soil faster when soil contains large particles like sand and rocks."
      },
      {
        "word": "macroinvertebrate",
        "definition": "Organisms that do not have a backbone and are visible without the aid of a microscope. Some macroinvertebrates live in streams and can be used to determine water quality.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/macroinvertebrate-large.jpg",
        "imageCaption": "Different species of macroinvertebrates",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/macroinvertebrate.mp4",
        "videoCaption": "Aquatic macroinvertebrates swimming around."
      },
      {
        "word": "porous",
        "definition": "A material, rock, or soil that has connected pores that allows liquids or gases (including water) to pass through. Porous land surfaces allow water to infiltrate into the ground. ",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/porous-high.jpg",
        "imageCaption": "This rock has many open spaces where water can accumulate or run through.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/porous.mp4",
        "videoCaption": "Water moves through the soil at different velocities depending on the soil porosity."
      },
      {
        "word": "nitrate",
        "definition": "A naturally occurring chemical from human and animal waste and decay that is a nutrient for plant growth. Nitrate is a pollutant when there is too much in the water and causes excessive plant and algae growth disrupting the natural balance. The EPA has a national standard for safe drinking water of less than 10ppm. ",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/nitrate-large.jpg",
        "imageCaption": "Fertilizer containing nitrate is applied to the soils to help plants grow, if fertilizer is not applied at the right time and the right ammounts it can reach the rivers and become a pollutant.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/nitrate.mp4",
        "videoCaption": "This pond received too much nitrate and now is full of algae. Algae in large amounts is harmful for the health of the organisms living in the pond."
      },
      {
        "word": "phosphate",
        "definition": "A naturally occurring chemical from manure and organic wastes, also found in fertilizers and soaps, that is a nutrient for plant growth. Excess phosphate can cause eutrophication and toxic algae blooms. ",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/phosphate-large.jpg",
        "imageCaption": "Excess of phosphate in rivers and lakes can cause the overgrowth of harmful algae.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/phosphate.mp4",
        "videoCaption": "This pond received too much phosphate and now is full of algae. Algae in large amounts is harmful for the health of the organisms living in the pond."
      },
      {
        "word": "ambient temperature",
        "definition": "The current air temperature, the overall temperature of the outdoor air that surrounds us. For accuracy, ambient temperature readings should always be taken in the shade.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/ambient-temperature-high.jpg",
        "imageCaption": "A thermometer measuring temperature.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/AmbientTemperature.mp4",
        "videoCaption": "A thermometer shows the cold conditions outside."
      },
      {
        "word": "aquatic",
        "definition": "An organism that lives in water.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/aquatic-high.jpg",
        "imageCaption": "Frogs begin their lives underwater as tadpoles.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/aquatic.mp4",
        "videoCaption": "Fish live in water too!"
      },
      {
        "word": "benthic",
        "definition": "The bottom of a body of water (river, stream, lake, or ocean).",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/benthic-high.jpg",
        "imageCaption": "This is the bottom of a river.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/benthic.mp4",
        "videoCaption": "The bottom of a river is where many organisms live."
      },
      {
        "word": "biological assessment",
        "definition": "A method of testing water quality by identifying the organisms in the water. If pollution sensitive organisms are found, then the indications are the waters are healthier.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/biological-assessment-high.jpg",
        "imageCaption": "This aquatic organism was collected from the river to help examine the water quality.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/biological-assessment.mp4",
        "videoCaption": "The scientist is collecting macroinvertebrates from the river, they are good indicators of the water quality because they do not like polluted water."
      },
      {
        "word": "divide",
        "definition": "The highest points of land (mountains, hills, or ridges) where runoff flows downhill in opposite directions defining the watershed boundaries. ",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/divide-high.jpg",
        "imageCaption": "Rain water runs in opposite directions from the highest point of the mountain.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/divide.mp4",
        "videoCaption": "These sharp edges of the mountains directs the rain water into different watersheds."
      },
      {
        "word": "land cover",
        "definition": "The physical material at the surface of the earth, including grass, pavement, trees, barren ground, crops, and water.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/landcover-high.jpg",
        "imageCaption": "Four different kinds of materials on the land",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/landcover.mp4",
        "videoCaption": "The earth surface is covered by different types of materials depending on human activities."
      },
      {
        "word": "macroinvertebrate ",
        "definition": "Organisms that do not have a backbone and are visible without the aid of a microscope. Some kinds of these of organisms live in streams and can be used to determine water quality.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/macroinvertebrate-large.jpg",
        "imageCaption": "Different kinds of aquatic organisms",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/macroinvertebrate.mp4",
        "videoCaption": "Aquatic organisms swimming around in bucket of stream water."
      },
      {
        "word": "pollution",
        "definition": "Chemicals, pathogens and other harmful things that could have a negative effect on people and other living things in an environment.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/pollution-high.jpg",
        "imageCaption": "Trash contaminates our rivers.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/pollution.mp4",
        "videoCaption": "Trash and other pollutants accumulate in the shore of this lake."
      },
      {
        "word": "relative humidity",
        "definition": "A ratio (expressed as a percentage) comparing the amount of water vapor contained in air at the current ambient temperature versus how much water vapor that same air would contain if it were completely saturated.  As air temperature increases, the amount of water vapor that could be contained also increases.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/relative-humidity-high.jpg",
        "imageCaption": "A difference between dry and wet conditions.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/relative-humidity.mp4",
        "videoCaption": "The air in the forest contains more water than the air in the dessert."
      },
      {
        "word": "wastewater treatment plant",
        "definition": "A facility that cleans human wastewater to remove contaminants before returning the water to the environment.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/sewage-treatment-plant-high.jpg",
        "imageCaption": "Wastewater from our homes gets cleaned in this facility before it gets to the river.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/SewageTreatmentPlant.mp4",
        "videoCaption": "In this facility, wastewater from our homes is cleaned before it is returned to the river."
      },
      {
        "word": "stormwater retention basin",
        "definition": "A long, channeled depression or trench that receives excess runoff during storms (such as from a parking lot) and has vegetation (such as grasses, flowering herbs, and shrubs) and organic matter (like mulch) to slow water infiltration and filter out pollutants.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/stormwater-retention-basin-high.jpg",
        "imageCaption": "In this neighborhood the pond collects and filters rainwater during storms.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/stormwater-retension-basin.mp4",
        "videoCaption": "This low area catches the rainwater to prevent flooding and has vegetation that helps clean up the water."
      },
      {
        "word": "sustainability",
        "definition": "An approach for human interactions that respects the value of the environment and employs methods of using resources wisely so they are not depleted or permanently damaged. Sustainably designed buildings conserve the use of resources such as water and energy.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/sustainability-lg.jpg",
        "imageCaption": "Human choices  and impacts can change the planet.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Sustainability.mp4",
        "videoCaption": "Impaired lands can be redeveloped to provide habitat for wildlife, areas for recreation, and protect water quality."
      },
      {
        "word": "topography",
        "definition": "The physical features or shape of the land (mountains, hills, valleys, etc.), that affect where water flows.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/topography-high.jpg",
        "imageCaption": "The mountains and hills direct the water to the river.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/topography.mp4",
        "videoCaption": "This river flows through the valley and carries water that came from the mountains."
      },
      {
        "word": "tributary",
        "definition": "A stream or river that flows into a larger stream, river, or lake.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/tributary-lg.jpg",
        "imageCaption": "A creek joins together with a larger river.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/Tributary.mp4",
        "videoCaption": "In this grassland we can see many creeks joining a larger river."
      },
      {
        "word": "turbidity",
        "definition": "A measure of the relative cloudiness (clarity) of the water that is caused by suspended particulate matter (inorganic and organic materials such as clay, silt, sand, and microscopic organisms). ",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/turbidity-high.jpg",
        "imageCaption": "The glasses contain water from the same stream. The glass on the right contains water collected after a storm. ",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/turbidity.mp4",
        "videoCaption": "The river with turbid water comes from an area were there was an erosion problem."
      },
      {
        "word": "pH",
        "definition": "A measurement of water quality based on the amount of hydrogen ions in water. The pH scale goes from 0 to 14 with 7 being neutral.  Below 7 is acidic and above seven is basic. ",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/ph-high.jpg",
        "imageCaption": "The scale ranges from acids to bases with neutral in the center.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/ph.mp4",
        "videoCaption": "Here we are testing to see if the fluids are acids or bases."
      },
      {
        "word": "precipitation",
        "definition": "Water that falls from the sky to the earth as rain, snow, sleet, or hail.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/precipitation-high.jpg",
        "imageCaption": "A strong rain storm.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/precipitation.mp4",
        "videoCaption": "Rain water falls on the vegetation."
      },
      {
        "word": "drinking water treatment plant",
        "definition": "A facility that cleans and purifies water from a source (rivers, lakes, reservoirs, or pumped up from underground aquifers through wells) to be used for human consumption.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/drinking-water-treatment-plant-lg.jpg",
        "imageCaption": "A series of tanks and filters clean the river water for the inhabitants of the city to use",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/drinking-water-treatment-plant.mp4",
        "videoCaption": "This facility cleans water to be used by humans in our homes, schools, and businesses."
      },
      {
        "word": "dissolved oxygen",
        "definition": "Oxygen that is mixed into the water and is available for aquatic organisms to absorb through their gills. Dissolved Oxygen is an important water quality parameter because aquatic organisms need oxygen to survive.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/dissolved-oxygen-large.jpg",
        "imageCaption": "Choppy (turbulent) water in rivers helps the oxygen from the atmosphere mix with the water.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/dissolved-oxygen.mp4",
        "videoCaption": "Riffles are areas where water has high oxygen content."
      },
      {
        "word": "organism",
        "definition": "A living thing such as a plant or an animal.",
        "image": "https://project-resources.concord.org/waters/Glossary/jpgs/high%20resolution/Organism2HiRes.png",
        "imageCaption": "Trees, birds, macroinvertebrates, fishes, and mushrooms are examples of organisms.",
        "video": "https://project-resources.concord.org/waters/Lesson2/Movies/OrganismFINAL.mov",
        "videoCaption": "There are many kinds of living things that live in different environments."
      },
      {
        "word": "biotic index",
        "definition": "A scale that shows the quality of the environment (e.g. a river or stream) based on the types of organisms found living there (e.g. aquatic macroinvertebrates).",
        "image": "https://project-resources.concord.org/waters/Glossary/jpgs/high%20resolution/NEWBioticIndexHi-res.png",
        "imageCaption": "Counting macroinvertebrates in the creek to see the health of the stream.",
        "video": "https://project-resources.concord.org/waters/Glossary/movies/BioticIndexFinal.m4v",
        "videoCaption": "Collecting and sorting critters to rate the health of the stream."
      },
      {
        "word": "constructed wastewater wetland",
        "definition": "A human-made marsh or swamp area designed to treat sewage or stormwater with wetland vegetation and natural biological processes that break down wastes and permeable soils that filter and clean the water.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/wastewater-wetland-high.jpg",
        "imageCaption": "Wetlands are a great way to filter water and return treated wastewater slowly to the environment.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/wastewater-wetland.mp4",
        "videoCaption": "Wetlands can be built next to wastewater treatment plants as a final step in the filtration process."
      },
      {
        "word": "mouth",
        "definition": "The end of a river where the water enters a lake, bay or ocean.",
        "image": "https://project-resources.concord.org/waters/Glossary/jpgs/high%20resolution/mouth-high.jpg",
        "imageCaption": "This river discharges directly into the ocean.",
        "video": "https://project-resources.concord.org/waters/Glossary/movies/mouth.mov",
        "videoCaption": "The satelite image shows a large river entering the ocean."
      },
      {
        "word": "confluence",
        "definition": "The place where two streams or rivers flow together and become a larger stream or river.",
        "image": "https://project-resources.concord.org/waters/Glossary/jpgs/high%20resolution/confluence-high.jpg",
        "imageCaption": "Two rivers are joining at this location and forming a larger river.",
        "video": "https://project-resources.concord.org/waters/Glossary/movies/confluence.mov",
        "videoCaption": "These two rivers of different colors are flowing together at this location."
      },
      {
        "word": "headwaters",
        "definition": "The small streams at the top of a watershed where the rivers begin, often called the source.",
        "image": "https://project-resources.concord.org/waters/Glossary/jpgs/high%20resolution/headwaters-high.jpg",
        "imageCaption": "Larger rivers start as small streams at the top of a watershed.",
        "video": "https://project-resources.concord.org/waters/Glossary/movies/headwaters.mov",
        "videoCaption": "This is where a very small stream starts to be a big river."
      },
      {
        "word": "floodplain",
        "definition": "An area of low-lying ground next to a river, formed mainly of river sediments and subject to flooding.",
        "image": "https://project-resources.concord.org/waters/Glossary/jpgs/high%20resolution/floodplain-high.jpg",
        "imageCaption": "When this river floods, it deposits sediments and nutrients in the surrounding crop land.",
        "video": "https://project-resources.concord.org/waters/Glossary/movies/floodplain.mov",
        "videoCaption": "The river has flooded the low-lying areas along its channel."
      },
      {
        "word": "vegetated infiltration basin",
        "definition": "A landscaped depression with permeable soils covered with plants that catches stormwater runoff to prevent flooding, enhance infiltration and evapotranspiration, and protect the quality of water in a watershed.",
        "image": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/jpgs/high%20resolution/vegetation-infiltration-basin-lg.jpg",
        "imageCaption": "This basin stores rain water during big storms.",
        "video": "https://cc-project-resources.s3.amazonaws.com/waters/Glossary/movies/vegetation-inflitration-basin.mp4",
        "videoCaption": "The basin has bushes and flowers and allows for the water to reach the soils instead of run overland to the rivers."
      }
    ],
    translations: {
      "es": {
        "cluster housing.word": "casas agrupadas",
        "cluster housing.definition": "Cuando los desarrolladores construyen una comunidad, ellos pueden construir las casas más juntas y dejar otras areas libres y sin construcción donde se pueden plantar árboles y otras plantas que ayudan a absorber la lluvia. Esto ayuda a reducir las innundaciones y permite que el agua de lluvia llegue al suelo.",
        "cluster housing.image_caption": "Espacio aierto compartido en un vecindario.",
        "cluster housing.video_caption": "Casas construidas muy juntas comparten jardines y zonas verdes.",
        "composting.word": "compostaje",
        "composting.definition": "Descomposición controlada de materia orgánica como lodos de depuradora, estiércol o residuos de cultivos en presencia de aire para formar un material similar al humus o suelo.",
        "composting.image_caption": "Sobros o desechos de comida utilizados para producir fertilizante orgánico",
        "composting.video_caption": "Sobros de comida que se usan para hacer fertilizante orgánico.",
        "conservation practice.word": "prácticas de conservación",
        "conservation practice.definition": "Medidas de control en forma de prácticas agrícolas de manejo, vegetativas y estructurales que reducen la escorrentía y la pérdida de suelo, facilitan la infiltración y absorción de contaminantes, y protegen la calidad del agua. También se conocen como buenas prácticas de gestión. ",
        "conservation practice.image_caption": "Todas estas actividades ayudan a mantener ríos saludables y sin contaminantes.",
        "conservation practice.video_caption": "Jardines de lluvia, agricultura sin labranza y superficies permeables son ejemplos de prácticas de conservación que ayudan a proteger la salud de los ríos.",
        "developed land.word": "terreno desarrollado",
        "developed land.definition": "Áreas donde los humanos hemos alterado el paisaje e instalado construcciones (asfalto, concreto, edificios, etc) sobre más del 30% del espacio.",
        "developed land.image_caption": "Acentamientos humanos cerca de los ríos.",
        "developed land.video_caption": "Muchas casas y carreteras construidas en terrenos vacios.",
        "elevation.word": "elevación",
        "elevation.definition": "La distancia sobre el nivel del mar.",
        "elevation.image_caption": "Montañas que se levantan sobre el nivel del mar.",
        "elevation.video_caption": "Las montañas se elevan sobre los valles.",
        "erosion.word": "erosión",
        "erosion.definition": "El desgaste de la superficie terrestre causado por el viento o el agua. Actividades como la agricultura  la desforestación y el desarrollo industrial y urbano intensifican este processo.",
        "erosion.image_caption": "Agua en movimiento causa que los suelos se laven.",
        "erosion.video_caption": "Durante un aguacero fuerte, el agua puede causar que la tierra se mobilize.",
        "evaporation.word": "evaporación",
        "evaporation.definition": "El proceso por el cual el agua pasa de estado líquido a estado gaseoso (vapor de agua) mediante la adición de calor. El vapor de agua consiste en moléculas de agua que permanecen suspendidas en el aire. El aire caliente tiene más energía y puede contener más moléculas de agua; es por esto que cuando hace calor se siente más humedad.",
        "evaporation.image_caption": "El agua del lago se convierte en niebla.",
        "evaporation.video_caption": "Conforme el día se calienta, el agua el el sendero se mueve hacia el aire.",
        "evapotranspiration.word": "evapotranspiración",
        "evapotranspiration.definition": "La combinación de dos procesos: el movimiento del agua de la tierra a la atmósfera mediante la transpiración de las plantas y la evaporación de agua del suelo y sistemas acuáticos. ",
        "evapotranspiration.image_caption": "Los bosques liberan humedad de los árboles y los suelos.",
        "evapotranspiration.video_caption": "Los bosques liberan humedad de los árboles y el suelo.",
        "flood .word": "inundación",
        "flood .definition": "Ocupación por parte del agua, de áreas que normalmente estarían secas debido al desbordamiento de los ríos.",
        "flood .image_caption": "Los ríos se desbordan cuando hay lluvias fuertes. ",
        "flood .video_caption": "Durante un aguacero fuerte las superficies de las carreteras no permiten que el suelo absorba el agua. ",
        "green roof.word": "techos verdes",
        "green roof.definition": "Una práctica de conservación que consiste en cubrir los techos de las construcciones con vegetación de manera parcial o total, sobre una membrana impermeable. También es posible que se instalen capas adicionales como por ejemplo: barreras para las raices y sistemas de irrigación.",
        "green roof.image_caption": "Césped y vegetación plantados sobre techos de edificios y casas.",
        "green roof.video_caption": "Los edificios en las cuidades pueden tener techos verdes.",
        "groundwater.word": "agua subterránea",
        "groundwater.definition": "Agua que se encuentra almacenada bajo tierra en las ranuras y espacios vacios existentes en el suelo, la arena, o las rocas llamados mantos acuíferos.",
        "groundwater.image_caption": "Un tubo metido en la tierra permite observar el agua el las capas profundas del suelo.",
        "groundwater.video_caption": "Los pozos nos permiten extraer el agua subterránea.",
        "impervious.word": "impermeable",
        "impervious.definition": "Área superficial que no tiene poros conectados y no permite que los líquidos y gases (incluyendo el agua) lleguen hasta el suelo, lo cual resulta en escorrentía durante un aguacero.",
        "impervious.image_caption": "Las carreteras y las aceras a menudo no permiten que el agua sea absorbida por el suelo.",
        "impervious.video_caption": "Los pozos se forman cuando el agua llovida no puede llegar al suelo.",
        "infrastructure.word": "infraestructura",
        "infrastructure.definition": "Estructuras físicas y organizacionales construidas por los seres humanos que son necesarias para el funcionamiento de una organización o sociedad.",
        "infrastructure.image_caption": "Tuberías debajo de las construcciones transportan el agua de lluvia y aguas residuales fuera del edificio.",
        "infrastructure.video_caption": "Este tipo de tuberias permiten que el agua se mueva muy rápido y genere electricidad.",
        "irrigation.word": "irrigación/riego",
        "irrigation.definition": "Proceso mediante el cual agua subterranea, de los ríos, o aguas residuales son aplicadas a los cultivos para proveerlos con los nutrientes y agua necesarios para su crecimiento.",
        "irrigation.image_caption": "Water from rivers or aquifers is spread on the crops to produce food.",
        "irrigation.video_caption": "Los cultivos reciben agua de un río cercano para ayudarlos a crecer.",
        "landfill.word": "relleno sanitario",
        "landfill.definition": "Sitio donde se entierran materiales de desecho. La basura en los rellenos sanitarios generalmente se distribuye en capas, se compacta lo mayor posible y se cubre con materiales de recubrimiento y tierra. ",
        "landfill.image_caption": "Basura de las casas o las industrias la cual no puede ser reutilizada o reciclada.",
        "landfill.video_caption": "El camión de la basura tira los desechos de nuestros vecindarios.",
        "nonpoint source pollution.word": "contaminación de fuente no puntual (contaminación difusa)",
        "nonpoint source pollution.definition": "La contaminación del agua puede venir de una fuente difusa que no se puede indentificar en un punto específico. Este tipo de contaminación comunmente se origina debido a la escorrentía que recoge y acarrea contaminantes naturales y sintéticos (fabricados por los seres humanos) hacia lagos, ríos, humedales, zonas costeras y mantos acuíferos. ",
        "nonpoint source pollution.image_caption": "Los peces no pueden sobrevivir si el agua está contaminada.",
        "nonpoint source pollution.video_caption": "La escorrentía transporta los contaminantes y la basura hacia nuestros ríos.",
        "no-till agriculture.word": "agricultura sin labranza",
        "no-till agriculture.definition": "Una práctica agricola de conservación en la que los agricultores cultivan sin disturbar los suelos o sin eliminar plantas existentes. La agricultura sin labranza mejora la infitración de los suelos, reduce la erosión, e incrementa el contenido de materia orgánica y el reciclado de los nutrientes en el suelo.",
        "no-till agriculture.image_caption": "Estos agricultores observan un cultivo que se planta para proteger el suelo.",
        "no-till agriculture.video_caption": "Los suelos agrícolas contienen más materia orgánica cuando se usa agricultura sin labranza.",
        "pervious.word": "permeable",
        "pervious.definition": "Área superficial que tiene poros conectados y permite que los líquidos y gases (incluyendo el agua) lleguen hasta el suelo.",
        "pervious.image_caption": "Este tipo de concreto (cemento, hormigón) permite que la lluvia pase a través de este. ",
        "pervious.video_caption": "El agua puede pasar a través de este material.",
        "photosynthesis.word": "fotosíntesis",
        "photosynthesis.definition": "Proceso mediante el cual las plantas y algunos microorganismos utilizan la luz solar para crear alimentos a partir de agua y dióxido de carbono. La fotosíntesis en las plantas generalmente requiere de un pigmento verde llamado clorofila y genera oxígeno como subproducto. ",
        "photosynthesis.image_caption": "Las plantas utilizan la energía solar a través de sus hojas para crecer.",
        "photosynthesis.video_caption": "Estas hojas están capturando la energía solar para hacer crecer a la planta. ",
        "point source pollution.word": "contaminación de fuente puntual",
        "point source pollution.definition": "Una fuente de contaminación especifica e identificable, como por ejemplo, un tubo, una acequia, una cuneta, o la chimenea de un barco o una fábrica.",
        "point source pollution.image_caption": "Tuberia de una fábrica transporta agua contaminada hacia un río.",
        "point source pollution.video_caption": "Esta tubería vierte agua contaminada en un río.",
        "porous paving.word": "pavimento poroso",
        "porous paving.definition": "Práctica de conservación en la cual áreas supeficiales tales como los parqueos o las aceras se construyen utilizando materiales porosos o con espacios entre bloques para permitir la infiltración del agua. Debajo de este tipo de pavimento generalmente se utiliza piedrilla para capturar el agua de lluvia hasta que sea absorbida por el suelo. ",
        "porous paving.image_caption": "Estos ladrillos separados por espacios vacios ayudan al agua a llegar al suelo.",
        "porous paving.video_caption": "Este parqueo está hecho de un material poroso que permite que el agua se pase al suelo.",
        "rain garden.word": "jardín de lluvia",
        "rain garden.definition": "Práctica de conservación para reducir la escorrentía. Un jardín de lluvia constiste en un hueco (hoyo) poco profundo que recoge el agua de lluvia que viene de techos, parqueos, o carreteras. En estos jardines se plantan arbustos, flores o césped nativos para incrementar la infiltración y evapotranspiración, filtrar contaminantes, y producir alimento y abrigo para mariposas, aves y otras formas de vida silvestre. Un tipo más complejo de jardines de lluvia son los estanques de bioretención que incluyen sistemas de drenaje y contienen suelos enriquecidos.  ",
        "rain garden.image_caption": "Las plantas y las flores ayudan al suelo a absorber el agua.",
        "rain garden.video_caption": "Los vecinos ayudan a construir un jardín de lluvia.",
        "runoff.word": "escorrentía",
        "runoff.definition": "Agua de lluvia que no es absorbida por el suelo y se mueve sobre la superficie de la tierra, la cual puede causar erosión y transportar contaminantes y sedimento hacia los ríos, lagos, alcantarillas, o estanques de agua llovida. ",
        "runoff.image_caption": "El agua de lluvia corre sobre la superficie del suelo.",
        "runoff.video_caption": "El agua de lluvia corre sobre la superficie del suelo.",
        "sediment.word": "sedimento",
        "sediment.definition": "Partículas derivadas de rocas o materiales biológicos que han sido transportadas, suspendidas o depositadas por el aire, agua, hielo, o que se acumulan mediante otros procesos naturales. Algunos tipos comunes de sedimento son: piedritas, arena, arcilla, sales, tierra de diatoméas.",
        "sediment.image_caption": "Las partículas finas se acumulan en el fondo del río en áreas donde el agua se mueve más lento.",
        "sediment.video_caption": "Durante los aguaceros fuertes, el agua erosiona el suelo llevandola hasta los ríos y provoca aguas turbias en los ríos.",
        "ambient temperature.word": "temperatura ambiente",
        "ambient temperature.definition": "La temperatura actual, la temperatura total de aire libre. Para que sean exactas. las medidas de temperatura se deben hacer a la sombra.",
        "ambient temperature.image_caption": "Un termómetro que mide la temperatura.",
        "ambient temperature.video_caption": "Un termómetro muestra las condiciones de frío afuera.",
        "sewage treatment plant.word": "planta de tratamiento de aguas residuales",
        "sewage treatment plant.definition": "Edificio municipal que purifica las aguas residuales producidas en las actividades humanas para eliminar los contaminantes antes de que sean retornadas al medio ambiente. ",
        "sewage treatment plant.image_caption": "El agua que desechamos en nuestros hogares es purificada en este sistema antes de ser vertida en el río.",
        "sewage treatment plant.video_caption": "En esta planta, el agua servida de nuestros hogares es purificada antes de ser vertida en el río.",
        "slope.word": "pendiente, Inclinación",
        "slope.definition": "El ángulo de la superficie terrestre en relación con la horizontal, el cual afecta el movimiento del agua. El agua fluye de elevaciones altas a elevaciones bajas, siguiendo la inclinación de la superficie terrestre. El agua fluye más rápido cuando la inclinación de la tierra es alta. ",
        "slope.image_caption": "Las superficies de las montañas no son planas sino inclinadas.  ",
        "slope.video_caption": "La inclinación de esta montaña es tan alta que el agua cae libremente por una cascada.",
        "temperature.word": "temperatura",
        "temperature.definition": "Medida de la cantidad de calor (energía cinética) un área determinada. ",
        "temperature.image_caption": "Este termómetro indica que hace mucho calor.",
        "temperature.video_caption": "La nieve se derrite conforme el día se calienta.",
        "transpiration.word": "transpiración",
        "transpiration.definition": "Proceso por el cual las plantas liberan agua a la atmósfera a través de poros llamados estomas que se encuentran en la superficie de las hojas, los tallos y las flores.",
        "transpiration.image_caption": "Las hojas de los árboles liberan agua a la atmósfera en forma de vapor.",
        "transpiration.video_caption": "La niña recolecta en la bolsa la humedad que las hojas liberan en forma de vapor.",
        "water quality criteria.word": "criterios de calidad del agua",
        "water quality criteria.definition": "Niveles de calidad de agua necesarios para que un sistema acuático (río, lago, humedal) se pueda utilizar para su uso designado. Estos criterios se basan en niveles específicos de contaminación que harían que el agua fuera dañina para el consumo humano, la produccion pesquera, los procesos industriales o las actividades recreativas como andar en bote y nadar. ",
        "water quality criteria.image_caption": "El/la laboratorista químico(a) analiza una muestra de agua para determinar la presencia de contaminantes.",
        "water quality criteria.video_caption": "Muchos ríos pequeños llegan a un río más grande.",
        "watershed.word": "cuenca hidrográfica",
        "watershed.definition": "Sistema definido por el área superficial sobre el cual el agua fluye montaña abajo a través de una serie de ríos y arroyos hasta un punto de salida común (río, lago, bahía u oceano). ",
        "watershed.image_caption": "Las montañas dirigen en agua hacia abajo y hasta un río.",
        "watershed.video_caption": "La pendiente de la montaña dirige toda el agua llovida hacia el lago.",
        "wetlands.word": "humedal",
        "wetlands.definition": "Áreas superficiales donde el suelo permanece húmedo o cubierto con agua durante la mayor parte del año. Puede que haya agua visible sobre la superficie o no. ",
        "wetlands.image_caption": "El agua permanece estancada en áreas naturales planas.",
        "wetlands.video_caption": "Agua poco profunda con plantas que prefieren vivir en suelo húmedo.",
        "drought.word": "sequía ",
        "drought.definition": "Escasez de agua debido a períodos muy largos sin precipitación. Las sequías pueden causar pérdida de vegetación e incendios forestales y reducir el almacenamiento de agua subterránea.",
        "drought.image_caption": "Los cultivos se pierden si no hay suficiencte lluvia.",
        "drought.video_caption": "La tierra que no recibe agua se vuelve infertil.",
        "soil group.word": "grupo de suelo",
        "soil group.definition": "Un sistema de clasificación usado para describir la capacidad del suelo de permitir la infiltración y el movimiento del agua a través de éste. Los suelos se clasifican desde infiltración rápida hasta infiltración muy lenta .",
        "soil group.image_caption": "Diferentes tipos de suelos",
        "soil group.video_caption": "Diferentes tipos de suelos",
        "infiltration.word": "infiltración",
        "infiltration.definition": "El proceso por el cual el agua es absorbida por el suelo.",
        "infiltration.image_caption": "Agua teñida con tinte azul fue vertida sobre el suelo, luego se hizo un hueco en el mismo lugar para ver que direcciones había seguido el agua. ",
        "infiltration.video_caption": "Los suelos drenan más rápido cuando contienen partículas grandes como piedras y árena.",
        "macroinvertebrate.word": "Macroinvertebrados",
        "macroinvertebrate.definition": "Organismos que no tienen columna vertebral y son visibles sin la ayuda de un microscopio. Algunos tipos de estos organismos viven en los ríos y pueden ser utilizados para determinar la calidad del agua. ",
        "macroinvertebrate.image_caption": "Diferentes tipos de organismos acuáticos",
        "macroinvertebrate.video_caption": "Macroinvertebrados acuáticos nadando en un cubo de agua del río.",
        "porous.word": "poroso",
        "porous.definition": "Material, roca, o suelo que tiene poros conectados los cuales permiten que los líquidos o gases (incluyendo el agua) atraviesen. Las áreas superficiales porosas permiten que el agua de lluvia sea absorbida por el suelo. ",
        "porous.image_caption": "Esta piedra tiene muchos espacios vacios por donde el agua puede pasar o acumularse.",
        "porous.video_caption": "El agua se mueve a través del suelo a diferentes velocidades dependiendo de la porosidad del suelo.",
        "vegetated infiltration basin.word": "deposito de infiltración con vegetación",
        "vegetated infiltration basin.definition": "Un estanque con suelos permeables cubierto con plantas que recoge la escorrentia durante un aguacero para prevenir las inundaciones, aumentar la inflitración y la evapotranspiración, y proteger la calidad del agua en una cuenca hidrográfica.",
        "vegetated infiltration basin.image_caption": "Este estanque almacena agua llovida durante aguaceros fuertes.",
        "vegetated infiltration basin.video_caption": "El estanque tiene arbustos y flores y permite que el agua llegue a la tierra en vez de correr por la superficie hasta los ríos.",
        "nitrate.word": "nitrato",
        "nitrate.definition": "Compuesto químico que existe de manera natural en el medio ambiente, se origina de desechos animales y vegetales y es un nutriente esencial para las plantas. El nitrato puede ser un contaminante cuando se encuentra en cantidades excesivas en el agua porque produce el crecimiento explosivo de algas y afecta el balance natural de los ríos, lagos, humedales, o zonas costeras. La US EPA (Agencia de Protección Ambiental de los Estados Unidos) tiene un estandar nacional para agua potable segura de menos de 10 partes por millón (ppm).",
        "nitrate.image_caption": "El tractor distribuye fertilizante en el campo que contiene nitrato para ayudar a los cultivos a crecer. Si el fertilizante no se aplica en el momento y las cantidades apropiadas, este puede llegar al río y convertirse en un contaminante.",
        "nitrate.video_caption": "Este lago recibió demasiado nitrato y ahora está lleno de algas. Las algas en grandes cantidades son dañinas para los organismos que viven en el lago.",
        "phosphate.word": "fosfato",
        "phosphate.definition": "Compuesto químico que existe de manera natural en el medio ambiente, se origina de desechos animales y vegetales y es un nutriente esencial para las plantas. El fosfato también se encuentra en fertilizantes y jabones. Cuando este compuesto se encuentra en cantidades excesivas en el agua puede causar crecimiento explosivo de algas y eutroficación en lagos, humedales, o zonas costeras.",
        "phosphate.image_caption": "El exceso de fosfato en los ríos y lagos puede causar el crecimiento descontrolado de algas dañinas.",
        "phosphate.video_caption": "Este lago recibió demasiado fosfato y ahora está lleno de algas. Las algas en grandes cantidades son dañinas para los organismos que viven en el lago.",
        "aquatic.word": "acuático",
        "aquatic.definition": "Un organismo que vive en el agua.",
        "aquatic.image_caption": "Las ranas comienzan su vida bajo el agua como renacuajos.",
        "aquatic.video_caption": "¡Los peces también viven en el agua!",
        "benthic.word": "béntico",
        "benthic.definition": "El fondo de un sistema acuático.",
        "benthic.image_caption": "Este es el fondo de un río.",
        "benthic.video_caption": "El fondo de un río es donde viven muchos organismos.",
        "biological assessment.word": "Evaluación biológica",
        "biological assessment.definition": "Un metodo para analizar la calidad de agua mediante la identificación de organismos que viven en el agua. Si se encuentran organismos sensibles a la contaminación, estos indican que el agua es más limpia.",
        "biological assessment.image_caption": "Este organismo acuático fue recolectado del río para ayudar a examinar la calidad del agua.",
        "biological assessment.video_caption": "El científico está recolectando macroinvertebrados de río, estos animalitos nos ayudan a saber sobre la calidad del agua porque muchos de ellos no pueden vivir en agua contaminada.",
        "divide.word": "división",
        "divide.definition": "Las crestas de las montañas que determinan la cuenca hidrográfica a la que contribuye la lluvia.",
        "divide.image_caption": "El agua de lluvia corre en direcciones opuestas desde el punto más alto de la montaña.",
        "divide.video_caption": "Los filos de estas montañas determinan la dirección que toma el agua de lluvia.",
        "landcover.word": "Cobertura de la tierra",
        "landcover.definition": "Los materiales físicos en la superficie de la tierra. Estos incluyen césped, pavimento, árboles, cultivos, y agua.",
        "landcover.image_caption": "Cuatro tipos diferentes de materiales físicos en la tierra",
        "landcover.video_caption": "La superficie de la tierra esta cubierta por diferentes tipos de materiales dependiendo de las actividades humanas que ahí se desarrollen.",
        "macroinvertebrate .word": "",
        "macroinvertebrate .definition": "",
        "macroinvertebrate .image_caption": "",
        "macroinvertebrate .video_caption": "",
        "pollution.word": "contaminación",
        "pollution.definition": "Sustancias químicas, patógenos u otras cosas dañinas que pueden tener efectos negativos en los seres humanos y los demás seres vivos. ",
        "pollution.image_caption": "La basura contamina nuestros ríos.",
        "pollution.video_caption": "Basura y otros contaminantes se acumulan a la orilla de este lago.",
        "relative humidity.word": "humedad relativa",
        "relative humidity.definition": "Una fracción (expresada como porcentaje) que compara la cantidad de vapor de agua contenido en el aire a temperatura ambiente con la cantidad de vapor de agua en el aire si éste estuviera saturado completamente. Conforme la temperatura aumenta, la cantidad de vapor de agua que el aire puede contener también aumenta. ",
        "relative humidity.image_caption": "Contraste entre condiciones secas y humedas.",
        "relative humidity.video_caption": "El aire en un bosque contiene mas agua que el aire en un desierto.",
        "wastewater treatment plant.word": "planta de tratamiento de aguas residuales",
        "wastewater treatment plant.definition": "Edificio municipal que purifica las aguas residuales producidas en las actividades humanas para eliminar los contaminantes antes de que sean retornadas al medio ambiente. ",
        "wastewater treatment plant.image_caption": "El agua que desechamos en nuestros hogares es purificada en este sistema antes de ser vertida en el río.",
        "wastewater treatment plant.video_caption": "En esta planta, el agua servida de nuestros hogares es purificada antes de ser vertida en el río.",
        "stormwater retention basin.word": "Estanque de retención de agua de lluvia",
        "stormwater retention basin.definition": "Estanque alargado que recibe exceso de escorrentia durante un aguacero (por ejemplo de un parqueo) y contiene vegetación (por ejemplo flores, césped, o arbustos) y materia orgánica (por ejemplo madera triturada o paja) para mejorar la infiltración y filtrar contaminantes.  ",
        "stormwater retention basin.image_caption": "En esta comunidad, el estanque recolecta y filtra el agua de lluvia cuando hay aguaceros fuertes ",
        "stormwater retention basin.video_caption": "Esta zona baja almacena agua de lluvia para prevenir inundaciones y tiene vegetación que ayuda a limpiar el agua.",
        "sustainability.word": "Sostenibilidad",
        "sustainability.definition": "Un enfoque de las interacciones humanas que respeta el valor del medio ambiente y en donde los recursos naturales son aprovechados moderadamente para evitar agotarlos o dañarlos de manera permanente. Los edificios diseñados de manera sostenible ayudan a conservar el uso de recursos como el agua y la energía eléctrica. ",
        "sustainability.image_caption": "Las decisiones humanas y sus consequencias pueden cambiar el planeta",
        "sustainability.video_caption": "Las decisiones humanas y sus consequencias pueden cambiar el planeta",
        "topography.word": "topografía",
        "topography.definition": "Atributos físicos o formas de la tierra (montañas, colinas, valles, etc.) que definen por donde fluye el agua.",
        "topography.image_caption": "Las montañas dirigen el agua al río",
        "topography.video_caption": "Este río fluye por el valle y lleva agua que viene de las montañas.",
        "tributary.word": "tributario",
        "tributary.definition": "Un río o arroyo que contribuye agua a un río más grande. ",
        "tributary.image_caption": "Un río o arroyo llega a otro río más grande. ",
        "tributary.video_caption": "Un río o arroyo llega a otro río más grande. ",
        "turbidity.word": "Turbidez",
        "turbidity.definition": "Medida de la claridad relativa del agua que es causada por la presencia de materia particulada en suspención (por ejemplo, arcilla, arena, y organismos microscópicos).",
        "turbidity.image_caption": "Los vasos contienen agua del mismo río, el vaso de la derecha fue recolectado después de un aguacero fuerte",
        "turbidity.video_caption": "Los vasos contienen agua del mismo río, el vaso de la derecha fue recolectado después de un aguacero fuerte",
        "pH.word": "pH",
        "pH.definition": "Medida de la calidad del agua basada en la cantidad de iones hidrógeno. La escala de pH va de 0 a 14. Un pH de 7 se considera neutro, un pH menor a cero es ácido y un pH mayor a cero es básico. ",
        "pH.image_caption": "Esta escala va de ácido a básico, y neutro es el centro.",
        "pH.video_caption": "Esta es una prueba para determinar si las sustancias son ácidos o bases.",
        "precipitation.word": "precipitación",
        "precipitation.definition": "El agua que cae del cielo a la tierra en forma de lluvia, nieve, aguanieve y granizo.",
        "precipitation.image_caption": "Un aguacero fuerte.",
        "precipitation.video_caption": "Agua de lluvia cae sobre la vegetación.",
        "drinking water treatment plant.word": "Planta de tratamiento de agua potable",
        "drinking water treatment plant.definition": "Edificio municipal que limpia y purifica el agua de alguna fuente (río, lago, acuífero) para ser usada para consumo humano",
        "drinking water treatment plant.image_caption": "Edificio municipal que limpia y purifica el agua de alguna fuente (río, lago, acuífero) para ser usada para consumo humano",
        "drinking water treatment plant.video_caption": "Esta planta limpia el agua para ser usada por los seres humanos en los hogares, escuelas y negocios. ",
        "dissolved oxygen.word": "oxígeno disuelto",
        "dissolved oxygen.definition": "Oxígeno mezclado con el agua que los organismos acuáticos pueden absorber a través de sus branquias. El oxígeno disuelto es un parametro de la calidad del agua muy importante porque los organismos acuáticos necesitan oxígeno para sobrevivir. ",
        "dissolved oxygen.image_caption": "La turbulencia en ríos como éste, ayuda al oxígeno del aire a mezclarse con el agua del río.",
        "dissolved oxygen.video_caption": "Los rápidos y cascadas son áreas donde el agua de los ríos contiene mucho oxígeno.",
        "cluster housing.word_mp3_url": "",
        "cluster housing.definition_mp3_url": "",
        "cluster housing.image_caption_mp3_url": "",
        "cluster housing.video_caption_mp3_url": "",
        "composting.word_mp3_url": "",
        "composting.definition_mp3_url": "",
        "composting.image_caption_mp3_url": "",
        "composting.video_caption_mp3_url": "",
        "conservation practice.word_mp3_url": "",
        "conservation practice.definition_mp3_url": "",
        "conservation practice.image_caption_mp3_url": "",
        "conservation practice.video_caption_mp3_url": "",
        "developed land.word_mp3_url": "",
        "developed land.definition_mp3_url": "",
        "developed land.image_caption_mp3_url": "",
        "developed land.video_caption_mp3_url": "",
        "elevation.word_mp3_url": "",
        "elevation.definition_mp3_url": "",
        "elevation.image_caption_mp3_url": "",
        "elevation.video_caption_mp3_url": "",
        "erosion.word_mp3_url": "",
        "erosion.definition_mp3_url": "",
        "erosion.image_caption_mp3_url": "",
        "erosion.video_caption_mp3_url": "",
        "evaporation.word_mp3_url": "",
        "evaporation.definition_mp3_url": "",
        "evaporation.image_caption_mp3_url": "",
        "evaporation.video_caption_mp3_url": "",
        "evapotranspiration.word_mp3_url": "",
        "evapotranspiration.definition_mp3_url": "",
        "evapotranspiration.image_caption_mp3_url": "",
        "evapotranspiration.video_caption_mp3_url": "",
        "flood .word_mp3_url": "",
        "flood .definition_mp3_url": "",
        "flood .image_caption_mp3_url": "",
        "flood .video_caption_mp3_url": "",
        "green roof.word_mp3_url": "",
        "green roof.definition_mp3_url": "",
        "green roof.image_caption_mp3_url": "",
        "green roof.video_caption_mp3_url": "",
        "groundwater.word_mp3_url": "",
        "groundwater.definition_mp3_url": "",
        "groundwater.image_caption_mp3_url": "",
        "groundwater.video_caption_mp3_url": "",
        "impervious.word_mp3_url": "",
        "impervious.definition_mp3_url": "",
        "impervious.image_caption_mp3_url": "",
        "impervious.video_caption_mp3_url": "",
        "infrastructure.word_mp3_url": "",
        "infrastructure.definition_mp3_url": "",
        "infrastructure.image_caption_mp3_url": "",
        "infrastructure.video_caption_mp3_url": "",
        "irrigation.word_mp3_url": "",
        "irrigation.definition_mp3_url": "",
        "irrigation.image_caption_mp3_url": "",
        "irrigation.video_caption_mp3_url": "",
        "landfill.word_mp3_url": "",
        "landfill.definition_mp3_url": "",
        "landfill.image_caption_mp3_url": "",
        "landfill.video_caption_mp3_url": "",
        "nonpoint source pollution.word_mp3_url": "",
        "nonpoint source pollution.definition_mp3_url": "",
        "nonpoint source pollution.image_caption_mp3_url": "",
        "nonpoint source pollution.video_caption_mp3_url": "",
        "no-till agriculture.word_mp3_url": "",
        "no-till agriculture.definition_mp3_url": "",
        "no-till agriculture.image_caption_mp3_url": "",
        "no-till agriculture.video_caption_mp3_url": "",
        "pervious.word_mp3_url": "",
        "pervious.definition_mp3_url": "",
        "pervious.image_caption_mp3_url": "",
        "pervious.video_caption_mp3_url": "",
        "photosynthesis.word_mp3_url": "",
        "photosynthesis.definition_mp3_url": "",
        "photosynthesis.image_caption_mp3_url": "",
        "photosynthesis.video_caption_mp3_url": "",
        "point source pollution.word_mp3_url": "",
        "point source pollution.definition_mp3_url": "",
        "point source pollution.image_caption_mp3_url": "",
        "point source pollution.video_caption_mp3_url": "",
        "porous paving.word_mp3_url": "",
        "porous paving.definition_mp3_url": "",
        "porous paving.image_caption_mp3_url": "",
        "porous paving.video_caption_mp3_url": "",
        "rain garden.word_mp3_url": "",
        "rain garden.definition_mp3_url": "",
        "rain garden.image_caption_mp3_url": "",
        "rain garden.video_caption_mp3_url": "",
        "runoff.word_mp3_url": "",
        "runoff.definition_mp3_url": "",
        "runoff.image_caption_mp3_url": "",
        "runoff.video_caption_mp3_url": "",
        "sediment.word_mp3_url": "",
        "sediment.definition_mp3_url": "",
        "sediment.image_caption_mp3_url": "",
        "sediment.video_caption_mp3_url": "",
        "sewage treatment plant.word_mp3_url": "",
        "sewage treatment plant.definition_mp3_url": "",
        "sewage treatment plant.image_caption_mp3_url": "",
        "sewage treatment plant.video_caption_mp3_url": "",
        "slope.word_mp3_url": "",
        "slope.definition_mp3_url": "",
        "slope.image_caption_mp3_url": "",
        "slope.video_caption_mp3_url": "",
        "temperature.word_mp3_url": "",
        "temperature.definition_mp3_url": "",
        "temperature.image_caption_mp3_url": "",
        "temperature.video_caption_mp3_url": "",
        "transpiration.word_mp3_url": "",
        "transpiration.definition_mp3_url": "",
        "transpiration.image_caption_mp3_url": "",
        "transpiration.video_caption_mp3_url": "",
        "water quality criteria.word_mp3_url": "",
        "water quality criteria.definition_mp3_url": "",
        "water quality criteria.image_caption_mp3_url": "",
        "water quality criteria.video_caption_mp3_url": "",
        "watershed.word_mp3_url": "",
        "watershed.definition_mp3_url": "",
        "watershed.image_caption_mp3_url": "",
        "watershed.video_caption_mp3_url": "",
        "wetlands.word_mp3_url": "",
        "wetlands.definition_mp3_url": "",
        "wetlands.image_caption_mp3_url": "",
        "wetlands.video_caption_mp3_url": "",
        "drought.word_mp3_url": "",
        "drought.definition_mp3_url": "",
        "drought.image_caption_mp3_url": "",
        "drought.video_caption_mp3_url": "",
        "soil group.word_mp3_url": "",
        "soil group.definition_mp3_url": "",
        "soil group.image_caption_mp3_url": "",
        "soil group.video_caption_mp3_url": "",
        "infiltration.word_mp3_url": "",
        "infiltration.definition_mp3_url": "",
        "infiltration.image_caption_mp3_url": "",
        "infiltration.video_caption_mp3_url": "",
        "macroinvertebrate.word_mp3_url": "",
        "macroinvertebrate.definition_mp3_url": "",
        "macroinvertebrate.image_caption_mp3_url": "",
        "macroinvertebrate.video_caption_mp3_url": "",
        "porous.word_mp3_url": "",
        "porous.definition_mp3_url": "",
        "porous.image_caption_mp3_url": "",
        "porous.video_caption_mp3_url": "",
        "vegetated infiltration basin.word_mp3_url": "",
        "vegetated infiltration basin.definition_mp3_url": "",
        "vegetated infiltration basin.image_caption_mp3_url": "",
        "vegetated infiltration basin.video_caption_mp3_url": "",
        "nitrate.word_mp3_url": "",
        "nitrate.definition_mp3_url": "",
        "nitrate.image_caption_mp3_url": "",
        "nitrate.video_caption_mp3_url": "",
        "phosphate.word_mp3_url": "",
        "phosphate.definition_mp3_url": "",
        "phosphate.image_caption_mp3_url": "",
        "phosphate.video_caption_mp3_url": "",
        "ambient temperature.word_mp3_url": "",
        "ambient temperature.definition_mp3_url": "",
        "ambient temperature.image_caption_mp3_url": "",
        "ambient temperature.video_caption_mp3_url": "",
        "aquatic.word_mp3_url": "",
        "aquatic.definition_mp3_url": "",
        "aquatic.image_caption_mp3_url": "",
        "aquatic.video_caption_mp3_url": "",
        "benthic.word_mp3_url": "",
        "benthic.definition_mp3_url": "",
        "benthic.image_caption_mp3_url": "",
        "benthic.video_caption_mp3_url": "",
        "biological assessment.word_mp3_url": "",
        "biological assessment.definition_mp3_url": "",
        "biological assessment.image_caption_mp3_url": "",
        "biological assessment.video_caption_mp3_url": "",
        "divide.word_mp3_url": "",
        "divide.definition_mp3_url": "",
        "divide.image_caption_mp3_url": "",
        "divide.video_caption_mp3_url": "",
        "landcover .word_mp3_url": "",
        "landcover .definition_mp3_url": "",
        "landcover .image_caption_mp3_url": "",
        "landcover .video_caption_mp3_url": "",
        "macroinvertebrate .word_mp3_url": "",
        "macroinvertebrate .definition_mp3_url": "",
        "macroinvertebrate .image_caption_mp3_url": "",
        "macroinvertebrate .video_caption_mp3_url": "",
        "pollution.word_mp3_url": "",
        "pollution.definition_mp3_url": "",
        "pollution.image_caption_mp3_url": "",
        "pollution.video_caption_mp3_url": "",
        "relative humidity.word_mp3_url": "",
        "relative humidity.definition_mp3_url": "",
        "relative humidity.image_caption_mp3_url": "",
        "relative humidity.video_caption_mp3_url": "",
        "wastewater treatment plant.word_mp3_url": "",
        "wastewater treatment plant.definition_mp3_url": "",
        "wastewater treatment plant.image_caption_mp3_url": "",
        "wastewater treatment plant.video_caption_mp3_url": "",
        "stormwater retention basin.word_mp3_url": "",
        "stormwater retention basin.definition_mp3_url": "",
        "stormwater retention basin.image_caption_mp3_url": "",
        "stormwater retention basin.video_caption_mp3_url": "",
        "sustainability.word_mp3_url": "",
        "sustainability.definition_mp3_url": "",
        "sustainability.image_caption_mp3_url": "",
        "sustainability.video_caption_mp3_url": "",
        "topography.word_mp3_url": "",
        "topography.definition_mp3_url": "",
        "topography.image_caption_mp3_url": "",
        "topography.video_caption_mp3_url": "",
        "tributary.word_mp3_url": "",
        "tributary.definition_mp3_url": "",
        "tributary.image_caption_mp3_url": "",
        "tributary.video_caption_mp3_url": "",
        "turbidity.word_mp3_url": "",
        "turbidity.definition_mp3_url": "",
        "turbidity.image_caption_mp3_url": "",
        "turbidity.video_caption_mp3_url": "",
        "pH.word_mp3_url": "",
        "pH.definition_mp3_url": "",
        "pH.image_caption_mp3_url": "",
        "pH.video_caption_mp3_url": "",
        "precipitation.word_mp3_url": "",
        "precipitation.definition_mp3_url": "",
        "precipitation.image_caption_mp3_url": "",
        "precipitation.video_caption_mp3_url": "",
        "drinking water treatment plant.word_mp3_url": "",
        "drinking water treatment plant.definition_mp3_url": "",
        "drinking water treatment plant.image_caption_mp3_url": "",
        "drinking water treatment plant.video_caption_mp3_url": "",
        "dissolved oxygen.word_mp3_url": "",
        "dissolved oxygen.definition_mp3_url": "",
        "dissolved oxygen.image_caption_mp3_url": "",
        "dissolved oxygen.video_caption_mp3_url": "",
        "organism.word": "Organismo",
        "organism.word_mp3_url": "",
        "organism.definition": "Un ser vivo, por ejemplo una planta o un animal.",
        "organism.definition_mp3_url": "",
        "organism.image_caption": "Árboles, pájaros, macroinvertebrados, peces, y hongos son ejemplos de organismos.",
        "organism.image_caption_mp3_url": "",
        "organism.video_caption": "Existen muchas clases de seres vivos habitando diferentes ambientes.",
        "organism.video_caption_mp3_url": "",
        "biotic index.word": "Índice biológico",
        "biotic index.word_mp3_url": "",
        "biotic index.definition": "Una escala que describe la calidad del ambiente (por ejemplo, un río) de acuerdo a los tipos de organismos presentes (por ejemplo, macroinvertebrados acuáticos).",
        "biotic index.definition_mp3_url": "",
        "biotic index.image_caption": "Contando bichitos del río para medir la salud del río.",
        "biotic index.image_caption_mp3_url": "",
        "biotic index.video_caption": "Recolectando y clasificando bichitos para medir la salud del río.",
        "biotic index.video_caption_mp3_url": "",
        "constructed wastewater wetland.word": "humedal de agua residual",
        "constructed wastewater wetland.word_mp3_url": "",
        "constructed wastewater wetland.definition": "Un humedal construido para tratar aguas residuales o agua llovida. Estos sistemas tienen vegetación propia de los humedales naturales y promueven los procesos biólogicos que descomponen los contaminantes. Además estos sistemas tienen suelos permeables que filtran y limpian el agua.",
        "constructed wastewater wetland.definition_mp3_url": "",
        "constructed wastewater wetland.image_caption": "Los humedales pueden filtrar contaminantes en aguas residuales antes de que regresen al medio ambiente.",
        "constructed wastewater wetland.image_caption_mp3_url": "",
        "constructed wastewater wetland.video_caption": "Es posible construir humedales al lado de plantas de tratamiento de aguas residuales que sirven como el paso final en el proceso de filtración.",
        "constructed wastewater wetland.video_caption_mp3_url": "",
        "main_prompt_mp3_url": "",
        "write_definition_mp3_url": "",
        "mouth.word": "boca/desembocadura",
        "mouth.word_mp3_url": "",
        "mouth.definition": "El final de un río donde el agua llega a un lago, una bahía o el oceano.",
        "mouth.definition_mp3_url": "",
        "mouth.image_caption": "Este río desemboca directo en el oceano.",
        "mouth.image_caption_mp3_url": "",
        "mouth.video_caption": "La imagen satelital muestra un río grande entrando al mar.",
        "mouth.video_caption_mp3_url": "",
        "confluence.word": "confluencia",
        "confluence.word_mp3_url": "",
        "confluence.definition": "Lugar donde dos ríos se juntan y se convierten en un solo río de mayor tamaño.",
        "confluence.definition_mp3_url": "",
        "confluence.image_caption": "En este lugar estos dos ríos se juntan para formar un río más grande.",
        "confluence.image_caption_mp3_url": "",
        "confluence.video_caption": "Estos dos ríos de diferente color se juntan en este punto.",
        "confluence.video_caption_mp3_url": "",
        "headwaters.word": "ríos de cabecera",
        "headwaters.word_mp3_url": "",
        "headwaters.definition": "Los ríos más pequeños en las partes más altas de la cuenca donde los ríos empiezan. ",
        "headwaters.definition_mp3_url": "",
        "headwaters.image_caption": "Todos los ríos comienzan como quebradas o riachuelos en la parte alta de la cuenca.",
        "headwaters.image_caption_mp3_url": "",
        "headwaters.video_caption": "Este riachuelo es donde comienza un río grande.",
        "headwaters.video_caption_mp3_url": "",
        "floodplain.word": "floodplain",
        "floodplain.word_mp3_url": "",
        "floodplain.definition": "Área plana a la orilla de un río formada principalmente por sedimentos y que está sujeta a inundaciones.",
        "floodplain.definition_mp3_url": "",
        "floodplain.image_caption": "Cuando este río se sale de su cauce, inunda las zonas cultivadas.",
        "floodplain.image_caption_mp3_url": "",
        "floodplain.video_caption": "El río se ha salido de su cauce e inundado las llanuras de la orilla.",
        "floodplain.video_caption_mp3_url": ""
      }
    }
  }
}
