// Generated from: https://poeditor.com/docs/languages
// using copy-paste and a few simple search & replace.
// IMPORTANT: Some language names has been intentionally modified to support some non-standard languages.
// E.g. Manx has been replaced with Yugtun (lang code gv). That way, translators can still use POEditor.

// NOTE: the translation mapping section of the README should be updated when this mapping code is updated.

export const CUSTOM_LANG_NAME_MAPPING: {[langName: string]: string} = {
  Manx: "Yugtun",
  Maori: "Athabaskan",
  Marathi: "Inupiaq"   // note, there is an ik code for Inupiaq but we want to reuse existing glossaries with mr
};

export const POEDITOR_LANG_CODE: {[langName: string]: string} = {
  "Abkhazian": "ab",
  "Afar": "aa",
  "Afrikaans": "af",
  "Akan": "ak",
  "Albanian": "sq",
  "Amharic": "am",
  "Arabic": "ar",
  "Arabic_AE": "ar-ae",
  "Arabic_BH": "ar-bh",
  "Arabic_DZ": "ar-dz",
  "Arabic_EG": "ar-eg",
  "Arabic_IQ": "ar-iq",
  "Arabic_JO": "ar-jo",
  "Arabic_KW": "ar-kw",
  "Arabic_LB": "ar-lb",
  "Arabic_LY": "ar-ly",
  "Arabic_MA": "ar-ma",
  "Arabic_OM": "ar-om",
  "Arabic_QA": "ar-qa",
  "Arabic_SA": "ar-sa",
  "Arabic_SY": "ar-sy",
  "Arabic_TN": "ar-tn",
  "Arabic_YE": "ar-ye",
  "Aragonese": "an",
  "Armenian": "hy",
  "Assamese": "as",
  "Asturian": "ast",
  "Avaric": "av",
  "Avestan": "ae",
  "Aymara": "ay",
  "Azerbaijani": "az",
  "Azerbaijani_Cyrillic": "az-cyrl",

  "Bambara": "bm",
  "Bashkir": "ba",
  "Basque": "eu",
  "Belarusian": "be",
  "Bengali": "bn",
  "Bihari_languages": "bh",
  "Bislama": "bi",
  "Bosnian": "bs",
  "Breton": "br",
  "Bulgarian": "bg",
  "Burmese": "my",

  "Catalan": "ca",
  "Chamorro": "ch",
  "Chechen": "ce",
  "Chichewa": "ny",
  "Chinese": "zh-CN",
  "Chinese_HK": "zh-hk",
  "Chinese_MO": "zh-mo",
  "Chinese_SG": "zh-sg",
  "Chinese_simplified": "zh-Hans",
  "Chinese_traditional": "zh-Hant",
  "Chinese_TW": "zh-TW",
  "Church_Slavic": "cu",
  "Chuvash": "cv",
  "Cornish": "kw",
  "Corsican": "co",
  "Cree": "cr",
  "Croatian": "hr",
  "Czech": "cs",

  "Danish": "da",
  "Dari": "prs",
  "Divehi": "dv",
  "Dutch": "nl",
  "Dzongkha": "dz",

  "English": "en",
  "English_AU": "en-au",
  "English_BZ": "en-bz",
  "English_CA": "en-ca",
  "English_GH": "en-gh",
  "English_HK": "en-hk",
  "English_IE": "en-ie",
  "English_IN": "en-in",
  "English_JM": "en-jm",
  "English_KE": "en-ke",
  "English_MU": "en-mu",
  "English_NG": "en-ng",
  "English_NZ": "en-nz",
  "English_PH": "en-ph",
  "English_SG": "en-sg",
  "English_TT": "en-tt",
  "English_UK": "en-gb",
  "English_US": "en-us",
  "English_ZA": "en-za",
  "English_ZW": "en-zw",
  "Esperanto": "eo",
  "Estonian": "et",
  "Ewe": "ee",

  "Faroese": "fo",
  "Fijian": "fj",
  "Filipino": "fil",
  "Finnish": "fi",
  "Flemish": "nl-be",
  "French": "fr",
  "French_BE": "fr-be",
  "French_CA": "fr-ca",
  "French_CH": "fr-ch",
  "French_LU": "fr-lu",
  "French_MC": "fr-mc",
  "Fulah": "ff",

  "Galician": "gl",
  "Ganda": "lg",
  "Georgian": "ka",
  "German": "de",
  "German_AT": "de-at",
  "German_BE": "de-be",
  "German_CH": "de-ch",
  "German_LI": "de-li",
  "German_LU": "de-lu",
  "Greek": "el",
  "Guarani": "gn",
  "Gujarati": "gu",

  "Haitian_Creole": "ht",
  "Hausa": "ha",
  "Hebrew": "he",
  "Herero": "hz",
  "Hindi": "hi",
  "Hiri_Motu": "ho",
  "Hungarian": "hu",

  "Icelandic": "is",
  "Ido": "io",
  "Igbo": "ig",
  "Indonesian": "id",
  "Interlingua": "ia",
  "Interlingue": "ie",
  "Inuktitut": "iu",
  "Inupiaq": "ik",
  "Irish": "ga",
  "Italian": "it",
  "Italian_CH": "it-ch",

  "Jamaican_Patois": "jam",
  "Japanese": "ja",
  "Javanese": "jv",

  "Kabyle": "kab",
  "Kalaallisut": "kl",
  "Kannada": "kn",
  "Kanuri": "kr",
  "Kashmiri": "ks",
  "Kazakh": "kk",
  "Khmer": "km",
  "Kikuyu_Gikuyu": "ki",
  "Kinyarwanda": "rw",
  "Kirghiz": "ky",
  "Komi": "kv",
  "Kongo": "kg",
  "Korean": "ko",
  "Kuanyama_Kwanyama": "kj",
  "Kurdish": "ku",

  "Lao": "lo",
  "Latin": "la",
  "Latvian": "lv",
  "Limburgish": "li",
  "Lingala": "ln",
  "Lithuanian": "lt",
  "Lojban": "jbo",
  "Luba-Katanga": "lu",
  "Luxembourgish": "lb",

  "Macedonian": "mk",
  "Malagasy": "mg",
  "Malay": "ms",
  "Malay_BN": "ms-bn",
  "Malayalam": "ml",
  "Maltese": "mt",
  "Manx": "gv",
  "Maori": "mi",
  "Marathi": "mr",
  "Marshallese": "mh",
  "Moldavian_Moldovan": "mo",
  "Mongolian": "mn",
  "Montenegrin": "me-me",
  "Montenegrin_Cyrillic": "me-cyrl",

  "Nauru": "na",
  "Navajo_Navaho": "nv",
  "Ndonga": "ng",
  "Nepali": "ne",
  "North_Ndebele": "nd",
  "Northern_Sami": "se",
  "Norwegian": "no",
  "Norwegian_Bokmål": "nb",
  "Norwegian_Nynorsk": "nn",

  "Occitan": "oc",
  "Ojibwa": "oj",
  "Oriya": "or",
  "Oromo": "om",
  "Ossetian_Ossetic": "os",

  "Pali": "pi",
  "Panjabi_Punjabi": "pa",
  "Persian": "fa",
  "Polish": "pl",
  "Portuguese": "pt",
  "Portuguese_BR": "pt-br",
  "Pushto_Pashto": "ps",

  "Quechua": "qu",

  "Romani": "rom",
  "Romanian": "ro",
  "Romansh": "rm",
  "Rundi": "rn",
  "Russian": "ru",
  "Rusyn": "ry",

  "Samoan": "sm",
  "Sango": "sg",
  "Sanskrit": "sa",
  "Sardinian": "sc",
  "Scottish_Gaelic": "gd",
  "Serbian": "sr",
  "Serbian_Cyrillic": "sr-cyrl",
  "Serbo-Croatian": "sh",
  "Shona": "sn",
  "Sichuan_Yi": "ii",
  "Sicilian": "scn",
  "Sindhi": "sd",
  "Sinhalese": "si",
  "Slovak": "sk",
  "Slovenian": "sl",
  "Somali": "so",
  "Sotho,_Southern": "st",
  "South_Ndebele": "nr",
  "Spanish": "es",
  "Spanish_AR": "es-ar",
  "Spanish_BO": "es-bo",
  "Spanish_CL": "es-cl",
  "Spanish_CO": "es-co",
  "Spanish_CR": "es-cr",
  "Spanish_DO": "es-do",
  "Spanish_EC": "es-ec",
  "Spanish_GT": "es-gt",
  "Spanish_HN": "es-hn",
  "Spanish_LA_C": "es-419",
  "Spanish_MX": "es-mx",
  "Spanish_NI": "es-ni",
  "Spanish_PA": "es-pa",
  "Spanish_PE": "es-pe",
  "Spanish_PR": "es-pr",
  "Spanish_PY": "es-py",
  "Spanish_SV": "es-sv",
  "Spanish_UY": "es-uy",
  "Spanish_VE": "es-ve",
  "Sundanese": "su",
  "Swahili": "sw",
  "Swati": "ss",
  "Swedish": "sv",
  "Swedish_FI": "sv-fi",

  "Tagalog": "tl",
  "Tahitian": "ty",
  "Tajik": "tg",
  "Tamil": "ta",
  "Tatar": "tt",
  "Telugu": "te",
  "Thai": "th",
  "Tibetan": "bo",
  "Tigrinya": "ti",
  "Tonga": "to",
  "Tsonga": "ts",
  "Tswana": "tn",
  "Turkish": "tr",
  "Turkmen": "tk",
  "Twi": "tw",

  "Uighur": "ug",
  "Ukrainian": "uk",
  "Urdu": "ur",
  "Uzbek": "uz",
  "Uzbek_Cyrillic": "uz-cyrl",

  "Venda": "ve",
  "Vietnamese": "vi",
  "Volapük": "vo",

  "Walloon": "wa",
  "Welsh": "cy",
  "Western_Frisian": "fy",
  "Wolof": "wo",

  "Xhosa": "xh",

  "Yiddish": "yi",
  "Yoruba": "yo",

  "Zhuang_Chuang": "za",
  "Zulu": "zu"
};

export const POEDITOR_LANG_NAME: {[langName: string]: string} = (() => {
  const result: {[langName: string]: string} = {};
  Object.keys(POEDITOR_LANG_CODE).forEach(langName => {
    const code = POEDITOR_LANG_CODE[langName];
    result[code] = CUSTOM_LANG_NAME_MAPPING[langName] || langName;
  });
  return result;
})();
